davinci_arm_gui_node:
  ros__parameters:
    topic_ns:
      real: "/davinci_arm/sim"
      sim: "/davinci_arm/sim"

    topics:
      telemetry:
        real_joint_states: "/joint_states"
        sim_joint_states: "/joint_states"

      commands:
        sim:
          shoulder_link_joint: "/shoulder_cmd_pos"
          bicep_link_joint: "/bicep_cmd_pos"
          arm_link_joint: "/arm_cmd_pos"
          wrist_link_joint: "/wrist_cmd_pos"
          end_effector_link_joint: "/end_effector_cmd_pos"

        real:
          shoulder_link_joint: "/shoulder_cmd_pos"
          bicep_link_joint: "/bicep_cmd_pos"
          arm_link_joint: "/arm_cmd_pos"
          wrist_link_joint: "/wrist_cmd_pos"
          end_effector_link_joint: "/end_effector_cmd_pos"
