davinci_arm_gui_node:
  ros__parameters:
    limits:
      # Angle limits (degrees):
      angle:
        min: 0.0
        max: 360.0

      # Motor speed limits (rad/s):
      motor_speed:
        min: -4.0
        max: 4.0

      # PWM limits (microseconds):
      pwm:
        min: 1000
        max: 2000

      # Duty cycle limits (percentage):
      duty:
        min: 0.0
        max: 100.0

      # Error between real and sim (degrees):
      error:
        min: -180.0
        max: 180.0

      # Error between actual angle and the ref angle (degrees):
      error_tracking:
        min: -180.0
        max: 180.0
